Repository stfc/aiida-mlip, pull requests merged in 2024-03, with the labels that each got.

#89 Fix coveralls reporting
  .github/workflows/ci.yml
  .gitignore
  pyproject.toml
Labels: bug, aiida-mlip

#90 Update CI
  .github/workflows/ci.yml
  .github/workflows/publish-on-pypi.yml
  .pre-commit-config.yaml
  docs/source/conf.py
  pyproject.toml
Labels: bug, documentation, aiida-mlip

#84 single point calcjob
  .github/workflows/ci.yml
  README.md
  aiida_mlip/__init__.py
  aiida_mlip/calculations.py
  aiida_mlip/calculations/__init__.py
  aiida_mlip/calculations/singlepoint.py
  aiida_mlip/cli.py
  aiida_mlip/data/__init__.py
  aiida_mlip/data/model.py
  aiida_mlip/helpers.py
  aiida_mlip/parsers.py
  conftest.py
  docs/source/apidoc/aiida_mlip.calculations.rst
  docs/source/apidoc/aiida_mlip.rst
  docs/source/conf.py
  docs/source/user_guide/calculations.rst
  docs/source/user_guide/data.rst
  docs/source/user_guide/get_started.rst
  docs/source/user_guide/index.rst
  examples/calculations/submit_singlepoint.py
  examples/example_01.py
  examples/input_files/__init__.py
  examples/input_files/file1.txt
  examples/input_files/file2.txt
  pyproject.toml
  tests/calculations/test_singlepoint.py
  tests/conftest.py
  tests/data/test_model.py
  tests/input_files/__init__.py
  tests/input_files/file1.txt
  tests/input_files/file2.txt
  tests/test_calculations.py
  tests/test_cli.py
  tox.ini
Labels: aiida-mlip

#95 Stop docs deployment on forks
  .github/workflows/docs.yml
Labels: bug, aiida-mlip

#98 Fix pytest and tox
  .github/workflows/ci.yml
  pyproject.toml
  tests/conftest.py
  tox.ini
Labels: bug, aiida-mlip
