Repository stfc/aiida-mlip, pull requests merged in 2024-02, with the labels that each got.

#44 Update docs links
  README.md
Labels: documentation

#61 Fix badges
  README.md
Labels: documentation

#67 Fix workflow indentation
  .github/workflows/publish-on-pypi.yml
Labels: bug

#70 Publish coverage to Coveralls
  .github/workflows/ci.yml
Labels: aiida-mlip

#75 Remove duplicate docs deployment
  .github/workflows/docs.yml
  README.md
Labels: documentation, aiida-mlip

#76 Fix tox for poetry
  .gitignore
  pyproject.toml
  tox.ini
Labels: bug, aiida-mlip

#77 Fix publishing to coveralls
  .github/workflows/ci.yml
Labels: bug, aiida-mlip

#82 Fix Python versions in CI
  .github/workflows/ci.yml
  .github/workflows/publish-on-pypi.yml
Labels: bug, aiida-mlip

#80 Data transfer #79
  .pre-commit-config.yaml
  aiida_mlip/data/model.py
  docs/source/apidoc/aiida_mlip.data.rst
  docs/source/apidoc/aiida_mlip.rst
  docs/source/user_guide/api.rst
  docs/source/user_guide/index.rst
  tests/data/input_files/model_local_file.txt
  tests/data/test_model.py
Labels: aiida-mlip
