Repository stfc/aiida-mlip, pull requests merged in 2025-07, with the labels that each got.

#188 Update workgraph
  aiida_mlip/workflows/ht_workgraph.py
  examples/tutorials/high_throughput_workgraph.ipynb
  pyproject.toml
  tests/workflows/test_ht.py
Labels: dependencies

#191 Add simple workgraph examples
  examples/tutorials/simple_workgraph.ipynb
Labels: documentation

#196 Fix building documentation
  .github/workflows/docs.yml
Labels: bug, documentation, dependencies

#194 Add citation file
  CITATION.cff
Labels: documentation

#199 Generate release notes in CI
  .github/workflows/publish-on-pypi.yml
Labels: documentation
