Repository stfc/aiida-mlip, pull requests merged in 2025-08, with the labels that each got.

#204 Update WorkGraph v0.6.0
  aiida_mlip/workflows/ht_workgraph.py
  examples/tutorials/high_throughput_workgraph.ipynb
  pyproject.toml
  tests/workflows/test_ht.py
Labels: dependencies

#210 Fix high throughput geomopt example
  examples/tutorials/high_throughput_workgraph.ipynb
Labels: bug, documentation

#208 Fix setting version
  aiida_mlip/__init__.py
Labels: bug, documentation

#179 Update pytest fixtures
  pyproject.toml
  tests/conftest.py
  tests/workflows/test_ht.py
Labels: dependencies

#220 Add calc kwargs input
  aiida_mlip/calculations/base.py
  docs/source/user_guide/calculations.rst
  docs/source/user_guide/tutorial.rst
  examples/calculations/submit_descriptors.py
  examples/calculations/submit_geomopt.py
  examples/calculations/submit_md.py
  examples/calculations/submit_singlepoint.py
  examples/tutorials/descriptors.ipynb
  examples/tutorials/geometry-optimisation.ipynb
  examples/tutorials/simple_workgraph.ipynb
  examples/tutorials/singlepoint.ipynb
  tests/calculations/configs/config_janus.yml
  tests/calculations/configs/config_janus_md.yml
  tests/calculations/configs/config_janus_sp.yml
  tests/calculations/test_descriptors.py
  tests/calculations/test_geomopt.py
  tests/calculations/test_md.py
  tests/calculations/test_singlepoint.py
  tests/data/test_config.py
  tests/utils.py
Labels: enhancement, breaking

#222 Add summary file to input and output spec
  aiida_mlip/calculations/base.py
  aiida_mlip/calculations/descriptors.py
  aiida_mlip/calculations/geomopt.py
  aiida_mlip/calculations/md.py
  aiida_mlip/calculations/singlepoint.py
  tests/calculations/test_descriptors.py
  tests/calculations/test_geomopt.py
  tests/calculations/test_md.py
  tests/calculations/test_singlepoint.py
Labels: enhancement
